### ISSUE TITLE
Webcam ReadSample() blocks after 11 ticks

### ISSUE THREAD

**Issue by pregnor** [sipsorcery/mediafoundationsamples#1]
In both the MFWebCamToFile and MFWebCamToH264Buffer projects you read the samples from the source reader with IMFSourceReader::ReadSample(...).

This takes the samples from a pool which provides around ~10 samples before it blocks (refuses to provide another). This happened to me with both samples (environment specifications at the end).

For the last parameter, the Sample, MSDN notes the following:
`ppSample [out]
Receives a pointer to the IMFSample interface or the value NULL (see Remarks). If this parameter receives a non-NULL pointer, the caller must release the interface.`

(https://msdn.microsoft.com/en-us/library/windows/desktop/dd374665(v=vs.85).aspx)

When the sample is not null after the ReadSample(...) call, it should be released inside the while loop.
Right after MFWebCamToFile.cpp#L150 and MFWebCamToH264Buffer.cpp#L256.

Environment: Windows 8.1 64b, Visual Studio Express 2013 for Windows Desktop.

**Comment by sipsorcery** [comment]
Thx for picking that up. I've added a release call to both those samples.

Not sure why you get blocking behaviour on your webcam. I've never experienced that. I've only ever run the samples on Windows 7.

**Comment by Epa222** [comment]
I guess they might have added the sample pool limitation around Windows 8 .

**Comment by TracyLestrade** [comment]
I Found the reason which leads this problem. when you call ReadSample  and you should Call SafeRelease(IMFSample) after copy buffer data.

**Comment by sipsorcery** [comment]
Yes not releasing the samples was the problem. Fixed.
