### ISSUE TITLE
Missing MFWebCamRTP vcxproj?

### ISSUE THREAD

**Issue by g40** [sipsorcery/mediafoundationsamples#2]
Hi, this is a nice resource. Good work. MFWebCamRTP appears to be missing though and I'm struggling with the correct CLR linker settings in VS2015. 

Thanks.

**Comment by chaome** [comment]
1. Compile the live555 projects, and copy the lib files to the project folder.
2. Create a new windows console project.
3. Add live555 include path:
..\externals\live555\BasicUsageEnvironment\include;
..\externals\live555\groupsock\include;
..\externals\live555\liveMedia\include;
..\externals\live555\UsageEnvironment\include

4. Modify "", add such lines:
//the missed lib
#pragma comment(lib, "WS2_32.Lib")

//live555 libs in Step1.
//#pragma comment(lib, "BasicUsageEnvironment.lib")
//#pragma comment(lib, "groupsock.lib")
//#pragma comment(lib, "liveMedia.lib")
//#pragma comment(lib, "UsageEnvironment.lib")

**Comment by chaome** [comment]
1. Create a new windows console project(C++) in the project folder "**MFWebCamRtp**", add the existing cpp file "MFWebCamRtp.cpp".

2. Modify the project property of "**MFWebCamRtp**", Add live555 folders to the **Include Path**:
..\externals\live555\BasicUsageEnvironment\include;
..\externals\live555\groupsock\include;
..\externals\live555\liveMedia\include;
..\externals\live555\UsageEnvironment\include

3. Modify "MFWebCamRtp.cpp", add such lines:
//the missed lib
#pragma comment(lib, "WS2_32.Lib")

//live555 libs
//#pragma comment(lib, "BasicUsageEnvironment.lib")
//#pragma comment(lib, "groupsock.lib")
//#pragma comment(lib, "liveMedia.lib")
//#pragma comment(lib, "UsageEnvironment.lib")

4. Compile the live555 projects(BasicUsageEnvironment, groupsock, liveMedia and UsageEnvironment), and copy them to the project folder.

**Comment by sipsorcery** [comment]
All project files are now present.
