### ISSUE TITLE
using MFSetAttributeSize function. 

### ISSUE THREAD

**Issue by Marslanali** [sipsorcery/mediafoundationsamples#7]
Hi,

I have been using MSF writer for saving video/audio using capture card. The problem is the video is saved with default width and size.

The function is as follow.

MFSetAttributeSize(pSrcOutMediaType, MF_MT_FRAME_SIZE, CAMERA_RESOLUTION_WIDTH, CAMERA_RESOLUTION_HEIGHT)

How ever video is still saved with default size.

Any insight on this issue?

**Comment by sipsorcery** [comment]
Isn't that line setting the output media type height and width to the same as your input?

Can you provide an abbreviated version of your code?

**Comment by Marslanali** [comment]
Hi,
Thank you for your response.

Here is the abbreviated version of my code for setting height and width.

HRESULT hr = S_OK;

static const int CAMERA_RESOLUTION_WIDTH =   1280;
static const int CAMERA_RESOLUTION_HEIGHT =  1024;

IMFMediaType *pSrcOutMediaType = NULL;

hr=MFCreateMediaType(&pSrcOutMediaType);
hr=MFSetAttributeSize(pSrcOutMediaType, MF_MT_FRAME_SIZE,CAMERA_RESOLUTION_WIDTH, CAMERA_RESOLUTION_HEIGHT);

Actually I have using the code generated from GraphEdit Plus for Video/Audio capturing and saving. The key thing is the ASF writer which save file, but I want to change the resolution (width, height) of my video file. I was trying with the above line of code, but still have no luck.

Attached is the code and I am setting MFSetAttributeSize() function in the following function of attached .cpp file.
 HRESULT BuildGraph(IGraphBuilder *pGraph, LPCOLESTR dstFile1); 	

[Recording_Test2.zip](https://github.com/sipsorcery/mediafoundationsamples/files/3903741/Recording_Test2.zip)

**Comment by Marslanali** [comment]
Hi sipsorcery,

I had solved the problem, thanks anyways for your help
