### ISSUE TITLE
MFEnumDeviceSources

### ISSUE THREAD

**Issue by mofo7777** [sipsorcery/mediafoundationsamples#8]
In MFUtility.h GetVideoSourceFromDevice :

hr = MFEnumDeviceSources(videoConfig, &videoDevices, &videoDeviceCount); can return S_OK, while videoDeviceCount is 0.

if videoDeviceCount is 0 :
hr = videoDevices[nDevice]->GetAllocatedString(MF_DEVSOURCE_ATTRIBUTE_FRIENDLY_NAME, &webcamFriendlyName, &nameLength); will segfault.

**Comment by sipsorcery** [comment]
Merci, fixed.

**Comment by mofo7777** [comment]
De rien, vous êtes français ?

**Comment by sipsorcery** [comment]
> De rien, vous êtes français ?

Non. Je parle un petit peu Français. I worked in Switzerland for a year and tried to learn a bit.

**Comment by mofo7777** [comment]
D'accord. C'était juste pour savoir si je pouvais m'exprimer,en français avec vous.
