### ISSUE TITLE
Memory leak in MFBitmapToEVR project

### ISSUE THREAD

**Issue by Rukhlov** [sipsorcery/mediafoundationsamples#9]
In the MFBitmapToEVR project, I found a memory leak when I called pStreamSink-> ProcessSample (pD3DVideoSample)
Moreover, it does not depend on the size of the displayed bitmap and occurs exclusively when calling ProcessSample (...) even when pD3DVideoSample is empty.
Memory leaks slowly (~1KB per call), but if the presentation is long enough then it becomes significant

**Comment by Rukhlov** [comment]
Similar problem https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/f8727e0d-2634-4ddf-9ce3-c7f54b55d914/standalone-evr-media-sink-and-memory-leak?forum=mediafoundationdevelopment

**Comment by sipsorcery** [comment]
I hadn't noticed the leak but then I only even managed to get the two EVR samples working less than a month ago.

I can confirm that I can get the memory leak behaviour as well. I can't see any likely culprits in the sample code. I tried a couple of redundant deallocations in the while loop but to no avail.

I had a look at the heap and the leaking allocations are 104 bytes and seem to always have the characters '#Pi' which means who knows what??

I don't have a solution to offer but if you do come across one would of course be interested to hear it.

![leak](https://user-images.githubusercontent.com/197660/73142882-92751580-408b-11ea-9bc9-94e4efd4ee0f.png)
![leak2](https://user-images.githubusercontent.com/197660/73142883-95700600-408b-11ea-9b36-c0b8397c6275.png)

**Comment by Rukhlov** [comment]
I had suspicion that a memory leak could be related to processing a message from streamSink i.e., сalling ProcessSample (...) is necessary after receiving the MEStreamSinkRequestSample message, but it also does not work
Very strange EVR behavior, AudioRenderer(SAR) has a very similar api usecase, but  no memory leaks..

**Comment by sipsorcery** [comment]
The leak doesn't happen when using the EVR with a `MFMediaSession`. The leak may be in the allocation of the Direct2D samples.

**Comment by Rukhlov** [comment]
most of the heap MFCreateMediaEvent и MFCreateMediaEventResult
![Heap1](https://user-images.githubusercontent.com/559417/73176491-9d788600-411d-11ea-8760-706da40055e6.png)

**Comment by mofo7777** [comment]
The solution is simple.

In MFBitmapToEVR.cpp Change this :

`
	CHECK_HR(pClock->Start(0), "Error starting presentation clock.");

	CHECK_HR(pD3DVideoSample->GetBufferByIndex(0, &pDstBuffer), "Failed to get destination buffer.");
	CHECK_HR(pDstBuffer->QueryInterface(IID_PPV_ARGS(&p2DBuffer)), "Failed to get pointer to 2D buffer.");

	while(bitmapCount < SAMPLE_COUNT)
	{
		printf("Attempting to write bitmap to EVR, sample count %d, sample duration %llu, sample time %llu.\n", bitmapCount, sampleDuration, llTimeStamp);

		if(bitmapCount % 2 == 0) {
			for(int i = 0; i < bitmapBufferLength; i += 4) {
				bitmapBuffer[i + 0] = 0x00;
				bitmapBuffer[i + 1] = 0xff;
				bitmapBuffer[i + 2] = 0x00;
				bitmapBuffer[i + 3] = 0x00;
			}
		}
		else {
			for(int i = 0; i < bitmapBufferLength; i += 4) {
				bitmapBuffer[i + 0] = 0xff;
				bitmapBuffer[i + 1] = 0x00;
				bitmapBuffer[i + 2] = 0x00;
				bitmapBuffer[i + 3] = 0x00;
			}
		}

		CHECK_HR(pD3DVideoSample->SetSampleTime(llTimeStamp), "Failed to set D3D video sample time.");
		CHECK_HR(pD3DVideoSample->SetSampleDuration(sampleDuration), "Failed to set D3D video sample duration.");
		CHECK_HR(p2DBuffer->ContiguousCopyFrom(bitmapBuffer, bitmapBufferLength), "Failed to copy bitmap to D2D buffer.");

		CHECK_HR(pStreamSink->ProcessSample(pD3DVideoSample), "Streamsink process sample failed.");

		Sleep(SAMPLE_DURATION / 10000);

		bitmapCount++;
		llTimeStamp += sampleDuration;
	}

	delete[] bitmapBuffer;

This is the optimized way of doing. The explaination is that you need to release interface after calling GetBufferByIndex and QueryInterface.`

**Comment by sipsorcery** [comment]
I applied that suggestion to the [MFBitmapToEVR sample](https://github.com/sipsorcery/mediafoundationsamples/blob/master/MFBitmapToEVR/MFBitmapToEVR.cpp) but the leak is still there. The durations and sample counts in the example have been set to make it run as fast as possible to generate the leak.

**Comment by Rukhlov** [comment]
![MemoryLeak](https://user-images.githubusercontent.com/559417/73215906-0be13680-4166-11ea-876e-63a0cf276568.PNG)
I tried, but the same result
memory leaks even if I don't fill pD3DVideoSample

**Comment by mofo7777** [comment]
Also, set this after "done" :

delete[] bitmapBuffer;
SAFE_RELEASE(p2DBuffer);
SAFE_RELEASE(pDstBuffer);

This does not explain the memory leak, but you have to do it, according to your CHECK_HR.

A different approach is needed to find the problem. I will try mine and let you know.

**Comment by mofo7777** [comment]
Normally you should see a difference with your first code, because you were not releasing after GetBufferByIndex and QueryInterface. But another memory leak can exist.

**Comment by mofo7777** [comment]
Hum ok.

[https://docs.microsoft.com/fr-fr/windows/win32/medfound/mestreamsinkrequestsample](url)

> Call this method when the stream sink sends an MEStreamSinkRequestSample event.

You force the IMFStreamSink::ProcessSample and don't handle MEStreamSinkRequestSample. Perhaps that's an explanation. You need to listen to StreamSink event.

**Comment by mofo7777** [comment]
I see another problem, you don't call UninitializeSampleAllocator

**Comment by mofo7777** [comment]
To Rukhlov.

Is this program leaks [https://github.com/mofo7777/Stackoverflow/tree/master/MFVideoEVR](url)

If not, handle MEStreamSinkRequestSample is not necessary.

**Comment by Rukhlov** [comment]
> 
> 
> To Rukhlov.
> 
> Is this program leaks [https://github.com/mofo7777/Stackoverflow/tree/master/MFVideoEVR](url)
> 
> If not, handle MEStreamSinkRequestSample is not necessary.

Yes, i tried this too :)

**Comment by mofo7777** [comment]
So does this program has memory leak ?

**Comment by Rukhlov** [comment]
> 
> 
> So does this program has memory leak ?

yes it has a memory leak

**Comment by mofo7777** [comment]
Thank you.

More investigations are needed...

**Comment by Rukhlov** [comment]
I found this problem in my .net project (https://github.com/Rukhlov/ScreenStreamer/blob/master/MediaToolkit/MediaFoundation/MfVideoRenderer.cs) and at the beginning I thought it was related to MediaFoundationWrapper, but now I see that this is a native EVR problem

**Comment by mofo7777** [comment]
I confirm, there is a memory leak. I will try to investigate the MEStreamSinkRequestSample event approach.

**Comment by mofo7777** [comment]
Ok, from my program, MFVideoEVR, I found the bug.

This is a Microsoft design problem, but it is documented :

[https://docs.microsoft.com/en-us/windows/win32/api/mfreadwrite/nf-mfreadwrite-imfsourcereader-setstreamselection](url)

> If you will not need data from one of the streams, it is a good idea to deselect that stream. If the stream is selected, the media source might hold onto a queue of unread data, and the queue might grow indefinitely, consuming memory.

So the strategy is just to only select the video stream :

`HRESULT hr = pSourceReader->SetStreamSelection((DWORD)MF_SOURCE_READER_ALL_STREAMS, FALSE);
if(FAILED(hr)){ goto done; }

hr = pSourceReader->SetStreamSelection((DWORD)MF_SOURCE_READER_FIRST_VIDEO_STREAM, TRUE);
if(FAILED(hr)){ goto done; }`

MFBitmapToEVR does not use the SourceReader, so the bug is different. But what I'm sure, it does not relate to pStreamSink->ProcessSample.

I will now investigate your bug.

**Comment by Rukhlov** [comment]
I check updated version of MFVideoEVR, there is still a memory leak
![MFVideoEVR_test](https://user-images.githubusercontent.com/559417/73310608-b1171000-4235-11ea-92e8-b76ae3606054.png)

I use ffmpeg generated test file
`ffmpeg -f lavfi -i testsrc=duration=3600:size=320x240:rate=30  -pix_fmt yuv420p testsrc.mp4`

and for speedup
```
Sleep(1); //Sleep(40);
....
hr = pD3DVideoSample->SetSampleTime(10000);//llTimeStamp);
```

**Comment by Rukhlov** [comment]
In my case, a memory leak was caused by IMFQualityManager and the events it sent,
to fix, need to query MediaEventGenerator from MediaSink, implement receive events and their ANNIHILATION !!! :bomb: :boom: :blush:

**Comment by Rukhlov** [comment]
so in MFVideoEVR you need to handle events from pStreamSink and pVideoSink, most likely it will solve a memory leak

**Comment by mofo7777** [comment]
@Rukhlov, your approach using the help of Visual Studio diagnostic tools is very good. I'm a fan.
You are right, handle events seems to disable all memory leaks. I updated MFVideoEVR.  Could you please confirm it's ok.

Thank you for your memory leak detection, and your workaround. Good job.

@sipsorcery, this should solve your memory leak too.

**Comment by Rukhlov** [comment]
> Could you please confirm it's ok.
I tried, the MFVideoEVR works fine

**Comment by sipsorcery** [comment]
I only had half an hour to spend on it. I've added a quick and dirty media event handler to the `MFBitmapToEVR` sample and while it seems to have reduced the rate of the leak it looks like it's still there.

I may have missed something in my callback class. It was a cut and paste job. Will have a closer look tomorrow.

**Comment by sipsorcery** [comment]
I've done a bit more analysis.

The good news is adding the event handler makes a substantial difference in reducing the memory leak. And as you can guess the bad news is that there is still a leak.

The two images below show before and after wiring up the `IMFMediaEventGenerator` on the video sink. In the `Before` case 62MB are allocated are 1 minute. In the `After` case it's down to 45MB after 1 minute.

![mfbmpevr_noevthandler](https://user-images.githubusercontent.com/197660/73435786-35a28500-4341-11ea-87ab-13f78880d132.png)

![mfbmpevr_withevthandler](https://user-images.githubusercontent.com/197660/73435792-389d7580-4341-11ea-9df7-2c3ea391e67d.png)

I guess it could be that there's another component generating events that need to be caught as well...

**Comment by sipsorcery** [comment]
I added an additional event handler to the stream sink and voila the leak is finally gone in `MFBitmapToEVR`. Unfortunately applying same change to `MFVideoEVR` doesn't remove the leak, probably another event generator somewhere.

![mfbmpevr_noleak](https://user-images.githubusercontent.com/197660/73436604-bf068700-4342-11ea-92e7-5bf19bb44e89.png)

**Comment by Rukhlov** [comment]
>  Unfortunately applying same change to `MFVideoEVR` doesn't remove the leak, probably another event generator somewhere.

I tried it yesterday, the program worked fine

**Comment by sipsorcery** [comment]
Fixed the leak in `MFVideoEVR` with:

````
pVideoReader->SetStreamSelection(MF_SOURCE_READER_ALL_STREAMS, false)
````

I am only using the video stream in my program. I guess if the audio stream is left active it still generates events that don't get caught.
